name: Build Compiler and Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Haxe environment
      uses: krdlab/setup-haxe@v1.5.1
      with:
        haxe-version: 4.3.1
    - name: Build Compiler
      run: haxe Release.hxml
